#!/bin/bash
# server=build.palaso.org
# project=Libraries
# build=icucil-win32-SILWritingSystems Continuous
# root_dir=..
# Auto-generated by https://github.com/chrisvire/BuildUpdate.
# Do not edit this file by hand!

cd "$(dirname "$0")"

# *** Functions ***
force=0
clean=0

while getopts fc opt; do
case $opt in
f) force=1 ;;
c) clean=1 ;;
esac
done

shift $((OPTIND - 1))

copy_auto() {
if [ "$clean" == "1" ]
then
echo cleaning $2
rm -f ""$2""
else
where_curl=$(type -P curl)
where_wget=$(type -P wget)
if [ "$where_curl" != "" ]
then
copy_curl $1 $2
elif [ "$where_wget" != "" ]
then
copy_wget $1 $2
else
echo "Missing curl or wget"
exit 1
fi
fi
}

copy_curl() {
echo "curl: $2 <= $1"
if [ -e "$2" ] && [ "$force" != "1" ]
then
curl -# -L -z $2 -o $2 $1
else
curl -# -L -o $2 $1
fi
}

copy_wget() {
echo "wget: $2 <= $1"
f=$(basename $2)
d=$(dirname $2)
cd $d
wget -q -L -N $1
cd -
}


# *** Results ***
# build: icucil-win32-SILWritingSystems Continuous (bt470)
# project: Libraries
# URL: http://build.palaso.org/viewType.html?buildTypeId=bt469
# VCS: https://github.com/sillsdev/icu-dotnet [icu54]
# dependencies:
# [0] build: icu4c-win32-minimal (bt471)
#     project: Libraries
#     URL: http://build.palaso.org/viewType.html?buildTypeId=Libraries_Icu4cWin32minim
#     clean: false
#     revision: latest.lastSuccessful
#     paths: {"icudt54.dll"=>"lib/icu", "icuin54.dll"=>"lib/icu", "icuuc54.dll"=>"lib/icu"}
# [1] build: palaso-win32-master Continuous (bt223)
#     project: libpalaso
#     URL: http://build.palaso.org/viewType.html?buildTypeId=bt223
#     clean: false
#     revision: latest.lastSuccessful
#     paths: {"Palaso.BuildTasks.dll"=>"bld"}
#     VCS: https://github.com/sillsdev/libpalaso.git [master]

# make sure output directories exist
mkdir -p ../bld
mkdir -p ../lib/icu

# download artifact dependencies
copy_auto http://build.palaso.org/guestAuth/repository/download/bt471/latest.lastSuccessful/icudt54.dll ../lib/icu/icudt54.dll
copy_auto http://build.palaso.org/guestAuth/repository/download/bt471/latest.lastSuccessful/icuin54.dll ../lib/icu/icuin54.dll
copy_auto http://build.palaso.org/guestAuth/repository/download/bt471/latest.lastSuccessful/icuuc54.dll ../lib/icu/icuuc54.dll
copy_auto http://build.palaso.org/guestAuth/repository/download/bt223/latest.lastSuccessful/Palaso.BuildTasks.dll ../bld/Palaso.BuildTasks.dll
# End of script
