<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Icu</RootNamespace>
    <AssemblyName>icu.net</AssemblyName>
    <Description>icu.net is a C# Wrapper around ICU4C</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.xml</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild" Version="6.0.5" PrivateAssets="all" />
    <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="all" />
    <PackageReference Include="SIL.ReleaseTasks" Version="3.0.0" PrivateAssets="all" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net451'">
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="2.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' != '.NETFramework'">
    <PackageReference Include="Microsoft.Extensions.DependencyModel" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <None Include="App.config" Pack="true" PackagePath="contentFiles\any\any\$(AssemblyTitle).dll.config" />
    <None Include="../../README.md" Pack="true" PackagePath="/">
      <Link>README.md</Link>
    </None>
  </ItemGroup>

  <Target Name="CollectRuntimeOutputs" BeforeTargets="_GetPackageFiles">
    <ItemGroup>
      <None Include="$(PackageId).props" Pack="true" PackagePath="build" />
      <None Include="$(PackageId).props" Pack="true" PackagePath="buildMultiTargeting" />
      <None Include="$(PackageId).targets" Pack="true" PackagePath="build" />
      <None Include="$(PackageId).targets" Pack="true" PackagePath="buildMultiTargeting" />
    </ItemGroup>
  </Target>

  <Target Name="StoreVersion" AfterTargets="Build" Condition="'$(IsCrossTargetingBuild)' == 'true'">
    <MakeDir Directories="$(MSBuildThisFileDirectory)/../../output/$(Configuration)" />
    <WriteLinesToFile File="$(MSBuildThisFileDirectory)/../../output/$(Configuration)/version.txt" Lines="$(GitVersion_FullSemVer)" Overwrite="True" Condition="'$(GitVersion_FullSemVer)' != ''" />
  </Target>
</Project>
