#!/bin/bash
HERE=`pwd`
TARGETS="lucid natty oneiric precise"
#PUBLISH='PALASO'
PUBLISH='LINGNET'
#REVISION=`echo $BUILD_NUMBER | sed -e 's/[:-].*$//'`
VARIANT='lingnet'
PRODUCT='libicu-cil'
ZIPTYPE='gz'
DEST=${HERE}/../output
BUILDINGDIR=${HERE}/../building

#NO_DPUT=1

BASE=$(dpkg-parsechangelog -lchangelog| grep ^Vers | cut -d\  -f2 | cut -d\- -f1 | cut -d\: -f2)
PKGVER=$(dpkg-parsechangelog -lchangelog| grep ^Vers | cut -d\  -f2 | cut -d\: -f2)


if [ "${TCTARGET}" = "lucid" ]; then
	xbuild /target:SourcePackage /p:Configuration=DebugMono /p:BUILD_NUMBER="${BASE}.abcd" /p:RootDir=$1 $1/bld/build.mono.proj  || exit $?
	cp $1/building/${PRODUCT}-${BASE}.tar.gz ~/upstream/${PRODUCT}_${BASE}.orig.tar.gz  || exit $?
	rm -rf ${DEST}/results
else
	rm ${BUILDINGDIR}/*build*
fi

source /home/bob/pbuilder/build.common

# create artifacts
if [ "${TCTARGET}" = "lucid" ]; then
	mkdir ${DEST}/results || exit $?
	cp /home/bob/pbuilder/results/lucid/${PRODUCT}_${PKGVER}.dsc ${DEST}/results || exit $?
	cp /home/bob/pbuilder/results/lucid/${PRODUCT}_${PKGVER}.debian.tar.gz ${DEST}/results || exit $?
	cp /home/bob/pbuilder/results/lucid/${PRODUCT}_${BASE}.orig.tar.gz ${DEST}/results || exit $?
	test -e ${DEST}/results/${PRODUCT}_${BASE}.orig.tar.gz || exit $?
fi
